In [102]:
# Make necessary imports
import numpy
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
from keras.utils import np_utils

# Select a consant seed to repeat the solution later
seed = 8
numpy.random.seed(seed)

#
X_train = [[0 , 0],[0 , 1],[1 , 0],[1 , 1]]
y_train = [0, 1, 1, 0]
X_train1 = X_train
X_train = numpy.array(X_train)
y_train = numpy.array(y_train)
X_test = X_train
y_test = y_train

# Introduce one hot encoding for each class
y_train = np_utils.to_categorical(y_train)
y_test = np_utils.to_categorical(y_test)


In [103]:
# Define a navie model
def naiveModel():
    # Create the model
    model = Sequential()
    # 1 hidden layer with same number of neurons as inputs
    model.add(Dense(5, input_dim = 2, kernel_initializer = 'normal', activation = 'relu'))
    # 1 Output softmax layer giving probability values for the 10 classes
    model.add(Dense(2, kernel_initializer = 'normal', activation = 'softmax'))
    # Compile the above model
    model.compile(loss = 'categorical_crossentropy', optimizer = 'adam', metrics = ['accuracy'])
    return model

In [104]:
modelInstance = naiveModel()

modelInstance.fit(X_train, y_train, validation_data = (X_test, y_test), epochs = 2000, batch_size = 1, verbose = 0)
for pred in X_train1:
    prediction = modelInstance.predict(numpy.array([pred]), verbose = 2)
    print(prediction)
scores = modelInstance.evaluate(X_test, y_test, verbose = 0)
print("Error : %.2f%%" % (100-scores[1]*100))

[[0.9818263  0.01817373]]
[[0.00643135 0.99356866]]
[[0.00689363 0.9931064 ]]
[[0.9940653  0.00593474]]
Error : 0.00%
